#!/bin/sh

case "$1" in 
	start)
		echo "Starting aesdsocket-start-stop"
		start-stop-daemon -S -n client -a /usr/bin/client -- -d
		;;
		stop)
		echo "Stopping aesdsocket-start-stop"
		start-stop-daemon -K -n client
		;;
		*)
		echo "Usage: $0 {start|stop}"
	exit1
esac
exit 0
